version: "3.9"

services:
  flask:
    build: ./fla
    container_name: flask
    command: python main.py runserver 0.0.0.0:5000
    ports:
      - '5000:5000'
    restart: unless-stopped
    links:
      - postgres_db
    depends_on:
      - postgres_db
  express:
    build: ./exp
    container_name: express
    restart: unless-stopped
    links:
      - postgres_db
    ports:
      - '3000:3000'
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres_db
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'

