version: "3.9"

services:
  flask:
    build: ./fla
    container_name: flask
    image: digitalocean.com/flask-python:3.6
    command: python main.py runserver 0.0.0.0:5000
    ports:
      - '5000:5000'
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres_db
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres_db
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
